application_id: "1362456388520906792"

# Activity type: 0 = Playing, 2 = Listening, 3 = Watching
type: 1

name: "Isabelle"
details: "I love you isa!"
state: "afk!"

# Images
largeImageKey: "embedded_background"
largeImageText: "Love you"
smallImageKey: "embedded_background"
smallImageText: "Subscribe"

# URL (optional, works only with certain types)
url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Pornhub-logo.svg/198px-Pornhub-logo.svg.png?20231111054238"

# Buttons (optional)
buttons:
  - name: "Visit Website"
    url: "https://www.nexoscreator.tech"
  - name: "GitHub Repo"
    url: "https://www.youtube.com"

# Custom status
custom_status: "if you're seeing this prolly not actually on lol"
custom_emoji: "🔥"
